[package]
name = "hft"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7"
itertools = "0.14"
quanta = "0.12"
rand = "0.9"
argh = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.27", features = ["derive"] }
eyre = "0.6"
color-eyre = "0.6"
human_format = "1.1"
core_affinity = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "std",
    "fmt",
    "ansi",
    "tracing-log",
    "parking_lot",
] }
pprof = { version = "0.15", default-features = false, features = ["flamegraph"] }

crossbeam-channel = "0.5"
rtrb = "0.3"
ringbuf = "0.4"
disruptor = "3.6"

[profile.release]
lto = true
# target-feature="+aes,+avx,+avx2,+avx512f,+fma,+sha,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3"

[profile.profiling]
inherits = "release"
strip = "debuginfo"
debug = true
